apiVersion: template.openshift.io/v1
kind: Template
# this is the service account that github actions or any other ci server can use to interact with openshift
metadata:
  name: github-cicd-credentials
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
      namespace: ${TOOLS_NAMESPACE}

  # Builder Service Account Role
  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      name: ${NAME}-builder
      labels:
        app: ${NAME}
      namespace: ${TOOLS_NAMESPACE}
    rules:
      - apiGroups:
          - template.openshift.io 
        resources:
          - processedtemplates
        verbs:
          - create
      - apiGroups:
          - apps.openshift.io 
        resources:
          - deploymentconfigs/instantiate
        verbs:
          - create
   
      - apiGroups:
          - build.openshift.io
          - ""
        resources:
          - buildconfigs/instantiate
        verbs:
          - create
      - apiGroups:
          - build.openshift.io
          - ""
        resources:
          - buildconfigs
        verbs:
          - patch
    
      - apiGroups:
          - build.openshift.io
          - ""
        resources:
          - buildconfigs
          - builds
        verbs:
          - delete
          - create
          - get
          - list
          - update
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - create
          - get
          - list
          - update
          - delete
          - patch
      - apiGroups:
          - image.openshift.io
          - ""
        resources:
          - imagestreamimages
          - imagestreamtags
        verbs:
          - create
          - get
          - delete
          - list
      - apiGroups:
          - image.openshift.io
          - ""
        resources:
          - imagestreams
        verbs:
          - get
          - list
          - patch
          - create
      - apiGroups:
          - build.openshift.io
          - ""  
        resources:
          - builds/log
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - build.openshift.io
        resources:
          - builds
        verbs:
          - get
          - list
          - watch

  # Deployer Role
  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      name: ${NAME}-deployer-dev
      labels:
        app: ${NAME}
      namespace: ${DEV_NAMESPACE}
    rules:
      - apiGroups:
          - template.openshift.io 
        resources:
          - processedtemplates
        verbs:
          - create
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
        verbs:
          - delete
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
        verbs:
          - get
          - list
          - update
          - watch
          - patch
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods
        verbs:
          - create
          - get
          - list
          - watch
          - delete
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods/log
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - events
        verbs:
          - list
      - apiGroups:
          - image.openshift.io
          - ""
        attributeRestrictions: null
        resources:
          - imagestreamtags
        verbs:
          - update
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers/scale
          - configmaps
          - secrets
          - services
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers/scale
        verbs:
          - update
      
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - configmaps
          - services
        verbs:
          - list
          - patch
          - create
          - patch
          - delete
      - apiGroups:
          - "route.openshift.io"
        attributeRestrictions: null
        resources:
          - routes
        verbs:
          - get
          - create
          - patch
          - delete
      - apiGroups:
          - "apps.openshift.io"
        attributeRestrictions: null
        resources:
          - deploymentconfigs
        verbs:
          - get
          - list
          - create
          - patch
          - delete
          - update
          - watch
      - apiGroups:
          - image.openshift.io
          - ""
        resources:
          - imagestreams
        verbs:
          - get
          - list
          - patch
          - create

  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      name: ${NAME}-deployer-test
      labels:
        app: ${NAME}
      namespace: ${TEST_NAMESPACE}
    rules:
      - apiGroups:
          - template.openshift.io 
        resources:
          - processedtemplates
        verbs:
          - create
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
        verbs:
          - delete
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
        verbs:
          - get
          - list
          - update
          - watch
          - patch
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods
        verbs:
          - create
          - get
          - list
          - watch
          - delete
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods/log
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - events
        verbs:
          - list
      - apiGroups:
          - image.openshift.io
          - ""
        attributeRestrictions: null
        resources:
          - imagestreamtags
          - imagestreams
        verbs:
          - update
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers/scale
          - configmaps
          - secrets
          - services
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers/scale
        verbs:
          - update
      
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - configmaps
          - services
        verbs:
          - patch
          - create
          - patch
          - delete
      - apiGroups:
          - "route.openshift.io"
        attributeRestrictions: null
        resources:
          - routes
        verbs:
          - get
          - create
          - patch
          - delete
      - apiGroups:
          - "apps.openshift.io"
        attributeRestrictions: null
        resources:
          - deploymentconfigs
        verbs:
          - get
          - list
          - create
          - patch
          - delete
          - update
          - watch
      - apiGroups:
          - image.openshift.io
          - ""
        resources:
          - imagestreams
        verbs:
          - get
          - list
          - patch
          - create
  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      name: ${NAME}-deployer-prod
      labels:
        app: ${NAME}
      namespace: ${PROD_NAMESPACE}
    rules:
      - apiGroups:
          - template.openshift.io 
        resources:
          - processedtemplates
        verbs:
          - create
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
        verbs:
          - delete
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
        verbs:
          - get
          - list
          - update
          - watch
          - patch
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods
        verbs:
          - create
          - get
          - list
          - watch
          - delete
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods/log
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - events
        verbs:
          - list
      - apiGroups:
          - image.openshift.io
          - ""
        attributeRestrictions: null
        resources:
          - imagestreamtags
        verbs:
          - update
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers/scale
          - configmaps
          - secrets
          - services
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers/scale
        verbs:
          - update
      
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - configmaps
          - services
        verbs:
          - patch
          - create
          - patch
          - delete
      - apiGroups:
          - "route.openshift.io"
        attributeRestrictions: null
        resources:
          - routes
        verbs:
          - get
          - create
          - patch
          - delete
      - apiGroups:
          - "apps.openshift.io"
        attributeRestrictions: null
        resources:
          - deploymentconfigs
        verbs:
          - get
          - list
          - create
          - patch
          - delete
          - update
          - watch
      - apiGroups:
          - image.openshift.io
          - ""
        resources:
          - imagestreams
        verbs:
          - get
          - list
          - patch
          - create

  # BUILDER ROLE BINDING
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-builder
      labels:
        app: ${NAME}
      namespace: ${TOOLS_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
    roleRef:
      kind: Role
      name: ${NAME}-builder
      namespace: ${TOOLS_NAMESPACE}
      apiGroup: authorization.openshift.io
    # dev deployer rolebinding
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-deployer-dev
      labels:
        app: ${NAME}
      namespace: ${DEV_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
        namespace: ${TOOLS_NAMESPACE}
    roleRef:
      kind: Role
      name: ${NAME}-deployer-dev
      namespace: ${DEV_NAMESPACE}
      apiGroup: authorization.openshift.io
  
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-deployer-test
      labels:
        app: ${NAME}
      namespace: ${TEST_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
        namespace: ${TOOLS_NAMESPACE}
    roleRef:
      kind: Role
      name: ${NAME}-deployer-test
      namespace: ${TEST_NAMESPACE}
      apiGroup: authorization.openshift.io
          
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-deployer-prod
      labels:
        app: ${NAME}
      namespace: ${PROD_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
        namespace: ${TOOLS_NAMESPACE}
    roleRef:
      kind: Role
      name: ${NAME}-deployer-prod
      namespace: ${PROD_NAMESPACE}
      apiGroup: authorization.openshift.io


  # IMAGE PULL BINDINGS
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-deployer-dev-image-puller
      labels:
        app: ${NAME}
      namespace: ${TOOLS_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: ${DEV_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: 'system:image-puller'

  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-deployer-dev-image-puller
      labels:
        app: ${NAME}
      namespace: ${TOOLS_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: ${TEST_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: 'system:image-puller'
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-deployer-dev-image-puller
      labels:
        app: ${NAME}
      namespace: ${TOOLS_NAMESPACE}
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: ${PROD_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: 'system:image-puller'

parameters:
  - displayName: Tools Namespace
    description: |
      The namespace where all of components of the
      credentials are stored.
    name: TOOLS_NAMESPACE
  - displayName: Production Namespace
    description: |
      The namespace where all of components of the
      credentials are stored.
    name: PROD_NAMESPACE
  - displayName: Test Namespace
    description: |
      The namespace where all of components of the
      credentials are stored.
    name: TEST_NAMESPACE
  - displayName: Dev Namespace
    description: |
      The namespace where all of components of the
      credentials are stored.
    name: DEV_NAMESPACE
    required: true
  - displayName: Credentials Name
    description: |
      The name used for all components of the 
      credentials.
    name: NAME
    required: true
    value: github-cicd
