apiVersion: v1
kind: Template
metadata:
  name: keycloak-service-account-secret
  annotations:
    description: "The Keycloak secret template that contains credentials for the KC service account"
  labels:
    app: devhub
    type: devhub-template
objects:
  # used by ci services to create dynamic keycloak clients for dev deployments of the devhub
- apiVersion: v1
  stringData:
    KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${NAME}
    labels:
      app: devhub
type: Opaque
parameters:
- description: The secret name
  displayName: name
  name: NAME
  required: true
  value: sso-dev-service-account
- description: The Key cloak service account client id
  displayName: Keycloak client id
  name: KEYCLOAK_CLIENT_ID
  required: true
- description: The service account secret
  displayName: Keycloak client secret
  name: KEYCLOAK_CLIENT_SECRET
  required: true
  
