kind: Template
apiVersion: v1
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}-nsp
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}-nsp
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
        name: deny-by-default
    spec:
        # The default posture for a security first namespace is to deny all traffic.
      podSelector: {}
      ingress: []
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
        name: intra-namespace-comms
    spec:
        # "allow ${NAMESPACE}-${ENVIRONMENT} namespace to talk to itself"
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                name: ${NAMESPACE}
                environment: ${ENVIRONMENT}
        podSelector: {}
        policyTypes:
            - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
        namespace: ${NAMESPACE}-${ENVIRONMENT}
        name: int-cluster-k8s-api-comms
    spec:
        # "allow ${NAMESPACE}-${ENVIRONMENT} pods to talk to the k8s api"
        podSelector:
          matchLabels:
            app: ${APP_NAME}
        ingress:
        - from:
          - namespaceSelector: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
    spec:
        # This policy allows any pod with a route & service combination
        # to accept traffic from the OpenShift router pods. This is
        # required for things outside of OpenShift (like the Internet)
        # to reach your pods.
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    network.openshift.io/policy-group: ingress
        podSelector: {}
        policyTypes:
          - Ingress
parameters:
  - description: The name for the application.
    displayName: Application Name
    name: APP_NAME
    required: true
  - description: The namespace
    displayName: Namespace
    name: NAMESPACE
    required: true
  - description: The environment
    displayName: environment
    name: ENVIRONMENT
    required: true