apiVersion: v1
kind: Template
metadata:
  name: github token secret template
  annotations:
    description: this template is used by the build time of the gatsby project
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: devhub-gh-token
      creationTimestamp: null
    data:
      GITHUB_TOKEN: '${GITHUB_TOKEN}'
parameters:
  - description: The github API token
    displayName: GITHUB_TOKEN
    required: true
