apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: sso-dev-service-account
  type: Opaque
parameters:
- description: The sso service account client id, as Service-Account
  displayName: KEYCLOAK_CLIENT_ID
  required: true
- description: The sso service account client secret
  displayName: KEYCLOAK_CLIENT_SECRET
  required: true
  