#!/bin/sh

# GatsD New Site
# Build docker with tag
# If no existing project, instal new template
# Initialize local node_modules with yarn


# shellcheck source=gatsd/_default.conf
. "$(dirname $0)/_default.conf"


##### FLAGS #####
tag=${BUILD_TAG}		# flag -t
port=${GATSBY_PORT}		# flag -p
host=${GATSBY_HOST}		# flag -H


##### CONSTANTS #####
SITE_NAME=${SITE_NAME}
GATSD_VERSION=${GATSD_VERSION}


##### FUNCTIONS #####
_help() {
	cat << HELP

########################################################
#                                                      #
#                     GatsD New                        # 
#                                                      #
########################################################

Build Docker container and initialize Gatsby project
for development.

gatsd new [OPTIONS] [ARGUMENT]

Options:
	-h		Print GatsD new help commands
			to console.
	-H		Set default host for new GatsD
			project.
			Default: ${GATSBY_HOST}
	-p		Set default port fornew GatsD
			project.
			Default: ${GATSBY_PORT}

Argument:
	site		Optional url for Gatsby site template.
			Must be a template url from github. Site
			argument is not needed when initializing
			GatsD into existing project.

			If site url isn't provided in an empty
			project, the site defauld will be used.
			Default: ${STARTER_URL}

Ex: ./gatsd new -p 8000 https://github.com/gatsbyjs/gatsby-starter-default

HELP
}


##### MAIN #####
[ "$1" = "new" ] && shift
while getopts ":h:H:p:t:-:" flag; do
	case "${flag}" in
		-)
			case "${OPTARG}" in
				help)
					_help
					exit 0
					;;
				*)
					echo "ERROR: Invalid flag ${flag}"
					exit 1
					;;
			esac
			;;
		h)
			_help
			exit 0
			;;
		H)
			host="${OPTARG}"
			;;
		p)
			port="${OPTARG}"
			;;
		t)
			tag="${OPTARG}"
			;;
		*)
			echo "ERROR: Invalid flag ${flag}"
			exit 1
			;;
	esac
done
shift `expr $OPTIND - 1`
[ "$1" = "new" ] && shift

echo "Starting to build docker container"
$(dirname $0)/docker-build -t "${tag}" -H "${host}" -p "${port}" || exit 1

echo "Initializing project."
$(dirname $0)/run gatsd new -H "${host}" -p "${port}" $@ || exit 1