apiVersion: v1
kind: Template
metadata:
  name: devhub caddyfile configmap template
  annotations:
    description: this config map template is used by the static deploy of the devhub
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: devhub-caddy
      creationTimestamp: null
    data:
      Caddyfile: |
        0.0.0.0:2015
        root /var/www/html
        log stdout
        errors stdout
        rewrite {
          if  {path} not_match ^\/0.0.0.0
          to  {path} {path}/ /?_url={uri}
        }
        templates {
          ext   .js
        }

        # gatsby_cache_control
        # https://www.gatsbyjs.org/docs/caching/
        header / {
          # prevent any static html from being cached
          Cache-Control "public, max-age=0, must-revalidate"
        }

        header /public/static {
          # all static assets SHOULD be cached
          Cache-Control "public, max-age=31536000, immutable"
        }

        header /public/static/sw.js {
          # special js file that should not be cached for offline mode
          Cache-Control "public, max-age=0, must-revalidate"
        }
parameters: []
