kind: Template
apiVersion: v1
objects:
  # this secret is made for deployment environments for the devhub not for tools namespace
  - apiVersion: v1
    data:
      GATSBY_ALGOLIA_SEARCH_KEY: ${ALGOLIA_SEARCH_KEY}
      GATSBY_ALGOLIA_APP_ID: ${ALGOLIA_APP_ID}
      GATSBY_ALGOLIA_INDEX_NAME_SUFFIX: ${SUFFIX}
    kind: Secret
    metadata:
      name: devhub-algolia-deployment
      labels:
        app: devhub
parameters:
- name: ALGOLIA_SEARCH_KEY
  description: The algolia search key used to query algolia at runtime
- name: ALGOLIA_APP_ID
  description: The algolia app id used by gatsby-plugin-algolia to push the index into
- name: SUFFIX
  description: The suffix provided to the algolia index to seperate our pr based builds