apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: debhub-app-web
labels:
  template: devhub-app-web
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}-static
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    minReadySeconds: 20 # should be ready for atleast 20 seconds before the container is considered available. This will allow us
    # to catch any errors on deploy before they are available to the web
    replicas: 3
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '1m'
          memory: '30Mi'
        limits:
          cpu: '2m'
          memory: '50Mi'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-static${SUFFIX}
      spec:
        containers:
        - image: ${NAME}-static:${VERSION}
          name: devhub-app-web
          args:
          - /tmp/scripts/run
          ports:
          - containerPort: 2015
            protocol: TCP
          resources:
            requests:
              cpu: '1m'
              memory: '30Mi'
            limits:
              cpu: '2m'
              memory: '50Mi'
          env:
          - name: SSO_BASE_URL
            value: ${SSO_BASE_URL_VALUE}
          - name: SSO_REALM_NAME
            value: ${SSO_REALM_NAME_VALUE}
          - name: SSO_CLIENT_ID
            value: ${SSO_CLIENT_ID_VALUE}
          volumeMounts:
          - name: ${VOLUMN_NAME}
            mountPath: /etc/Caddyfile
            readOnly: true
            subPath: Caddyfile
        volumes:
        - name: ${VOLUMN_NAME}
          configMap:
            defaultMode: 420
            name: ${NAME}-caddy
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - devhub-app-web
        from:
          kind: ImageStreamTag
          name: ${NAME}-static:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    ports:
    - name: web
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/disable_cookies: 'true'
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    host:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}-static${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: devhub-app-web
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: A name used for routes/services and deployment configs
  displayName: Host
  name: HOST
  required: false
  value: ''
- description: A base url of sso in the env
  displayName: sso base URL
  name: SSO_BASE_URL_VALUE
  required: false
  value: ''
- description: A sso client id in the env
  displayName: sso client id
  name: SSO_CLIENT_ID_VALUE
  required: false
  value: ''
- description: A sso realm name in the env
  displayName: sso realm name
  name: SSO_REALM_NAME_VALUE
  required: false
  value: ''
- description: A volumn used for the caddy from config map
  displayName: volumn name
  name: VOLUMN_NAME
  required: false
  value: web-caddy-config
