apiVersion: v1
kind: Template
metadata:
  name: event-brite-secret
  namespace: ${NAME_SPACE}
  annotations:
    description: "The Eventbrite api key secret template"
  labels:
    app: devhub
    type: devhub-template
objects:
- apiVersion: v1
  stringData:
    EVENT_BRITE_API_KEY: ${EVENT_BRITE_API_KEY}
  apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: devhub-eventbrite-token
    labels:
      app: devhub
parameters:
- description: The CSI Lab event brite access token
  displayName: Eventbrite-key
  name: EVENT_BRITE_API_KEY
  required: true
- description: The namespace the secret will be added too
  displayName: namespace
  name: NAME_SPACE
  required: true
  value: devhub-tools