apiVersion: v1
kind: Template
metadata:
  name: keycloak-service-account-secret
  annotations:
    description: "The Matomo api key secret template"
  labels:
    app: devhub
    type: devhub-template
objects:
- apiVersion: v1
  data:
    KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${NAME}
    labels:
      app: devhub
type: Opaque
parameters:
- description: The secret name
  displayName: name
  name: NAME
  required: true
  value: sso-dev-service-account
- description: The Key cloak service account client id
  displayName: Keycloak client id
  name: KEYCLOAK_CLIENT_ID
  required: true
- description: The service account secret
  displayName: Keycloak client secret
  name: KEYCLOAK_CLIENT_SECRET
  required: true
  
