apiVersion: v1
kind: Template
metadata:
  name: matomo-secret
  namespace: ${NAME_SPACE}
  annotations:
    description: "The Matomo api key secret template"
  labels:
    app: devhub
    type: devhub-template
objects:
- apiVersion: v1
  stringData:
    MATOMO_API_KEY: ${MATOMO_API_KEY}
  apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: matomo-api-key
    labels:
      app: devhub
parameters:
- description: The devhub matomo prod api key
  displayName: Matomo Api Key
  name: MATOMO_API_KEY
  required: true
- description: The namespace the secret will be added too
  displayName: namespace
  name: NAME_SPACE
  required: true
  value: devhub-tools
  