kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    stringData:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER_EMAIL: ${GITHUB_USER_EMAIL}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
    kind: Secret
    metadata:
      name: ${NAME}-github
      labels:
        app: ${NAME}
        rootComponent: ${NAME}
parameters:
  - name: NAME
    value: devhub-api
    description: the component name
    displayName: Name
  - name: GITHUB_TOKEN
    required: true 
    displayName: Github Token
  - name: GITHUB_USER_EMAIL
    required: true 
  - name: GITHUB_USERNAME
    required: true 