export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';

// SIPHON ACTIONS
export const LOAD_SIPHON_NODES = 'LOAD_SIPHON_NODES';
export const LOAD_SIPHON_NODES_SUCCESS = 'LOAD_SIPHON_NODES_SUCCESS';
export const LOAD_SIPHON_NODES_FAIL = 'LOAD_SIPHON_NODES_FAIL';
export const FILTER_SIPHON_NODES = 'FILTER_SIPHON_NODES';
export const FILTER_SIPHON_NODES_BY_FILTER_LIST = 'FILTER_SIPHON_NODES_BY_FILTER_LIST';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
// UI ACTIONS
export const SET_SELECTED_FILTER_OPTION = 'SET_SELECTED_FILTER_OPTION';
export const TOGGLE_MAIN_NAVIGATION = 'TOGGLE_MAIN_NAVIGATION';
