export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';

// SIPHON ACTIONS
export const LOAD_SIPHON_COLLECTIONS = 'LOAD_SIPHON_COLLECTIONS';
export const FILTER_SIPHON_NODES_BY_FILTER_LIST = 'FILTER_SIPHON_NODES_BY_FILTER_LIST';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_BAR_TERMS = 'SET_SEARCH_BAR_TERMS';
export const RESET_SEARCH = 'RESET_SEARCH';
// UI ACTIONS
export const TOGGLE_MAIN_NAVIGATION = 'TOGGLE_MAIN_NAVIGATION';
export const SET_WELCOME_PANEL_VIEWED = 'SET_WELCOME_PANEL_VIEWED';
