export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';

// SIPHON ACTIONS
export const LOAD_SIPHON_NODES = 'LOAD_SIPHON_NODES';
export const LOAD_SIPHON_NODES_SUCCESS = 'LOAD_SIPHONE_NODES_SUCCESS';
export const LOAD_SIPHON_NODES_FAIL = 'LOAD_SIPHONE_NODES_FAIL';
