apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: searchgate-credentials-template
objects:
- apiVersion: v1
  stringData:
    githubAuthtoken: ${GITHUB_AUTH_TOKEN}
  kind: Secret
  metadata:
    name: searchgate-credentials
  type: Opaque
parameters:
- description: GitHub authentication token used to access the GitHub API
  displayName: GitHub authentication token
  name: GITHUB_AUTH_TOKEN
  required: true
