apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: debhub-app-web
labels:
  template: devhub-app-web
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}-static
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-static${SUFFIX}
      spec:
        containers:
        - image: ${NAME}-static:${VERSION}
          name: devhub-app-web
          ports:
          - containerPort: 2015
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          command: ["/bin/sh","-c"]
          # args: ["pwd"]
          # args: ["cd xxx; ./kc-create-client.sh xxx"]
          env:
            - name: KEYCLOAK_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: keycloak-service-account
                    key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: keycloak-service-account
                    key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_URL
              value: ${SSO_URL}
            - name: REALM_NAME
              value: ${SSO_REALM_NAME}
            - name: PR_NUMBER
              value: ${PR}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - devhub-app-web
        from:
          kind: ImageStreamTag
          name: ${NAME}-static:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    ports:
    - name: web
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    host:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}-static${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: devhub-app-web
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: A name used for routes/services and deployment configs
  displayName: Host
  name: HOST
  required: false
  value: ''
- description: The base url of keycloak sso
  displayName: sso_url
  name: SSO_URL
  required: false
  value: ''
- description: The client of keycloak sso
  displayName: sso_client_id
  name: SSO_CLIENT_ID
  required: false
  value: ''
- description: The realm of keycloak sso
  displayName: sso_realm_name
  name: SSO_REALM_NAME
  required: false
  value: ''
- description: The pull request number, if exist
  displayName: pr
  name: PR
  required: false
  value: ''