name: End-to-end tests
on: 
  pull_request:
    paths:
    - 'web'
paths:
  - '.github/actions/devhub-markdown-frontmatter-verify/**/*.js'
  - 'web/journeyRegistry/*.json'
  - 'web/topicRegistry/*.json'
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: web
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: patricksimonian/github-action@6dc0f8790dccace7167b12f9aaa0e28b7dc81c7c 
        with:
          working-directory: web
          start: npm run dev
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          config: baseUrl=http://localhost:8000
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_BRITE_API_KEY: ${{secrets.EVENT_BRITE_API_KEY}}
          GATSBY_SSO_BASE_URL: https://dev.oicd.gov.bc.ca
          GATSBY_ALGOLIA_APP_ID: ${{secrets.GATSBY_ALGOLIA_APP_ID}}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
          GATSBY_ALGOLIA_INDEX_NAME_SUFFIX: local
          GATSBY_SEARCHGATE_API_URL: https://searchgate-test.pathfinder.gov.bc.ca
