name: "devhub-markdown-verify-test"
on:
  pull_request:
    paths:
    - 'web/journeyRegistry/*.json'
    - 'web/topicRegistry/*.json'
jobs:
  test:
    name: Running the frontmatter verifier
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/devhub-markdown-frontmatter-verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo: devhub-app-web
        owner: bcgov
        throttle: 1000
