kind: Template
apiVersion: v1
objects:
  # this secret is made for builds (the tools environment)on the devhub not for deployment namespaces
  - apiVersion: v1
    stringData:
      ALGOLIA_ADMIN_KEY: ${ALGOLIA_ADMIN_KEY}
      GATSBY_ALGOLIA_SEARCH_KEY: ${GATSBY_ALGOLIA_SEARCH_KEY}
      GATSBY_ALGOLIA_APP_ID: ${GATSBY_ALGOLIA_APP_ID}
    kind: Secret
    metadata:
      name: devhub-algolia-build
      labels:
        app: devhub
parameters:
- name: ALGOLIA_ADMIN_KEY
  description: The algolia admin key used by gatsby-plugin-algolia
- name: GATSBY_ALGOLIA_APP_ID
  description: The algolia app id used by gatsby-plugin-algolia to push the index into
- name: GATSBY_ALGOLIA_SEARCH_KEY
  description: The algolia api search key used by gatsby-plugin-algolia to push the index into