apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: devhub-app-web-bc-template
labels:
  template: devhub-app-web
objects:
- apiVersion: v1
  data:
    features.json: |-
      {
        "dynamicSearch": {
          "github": ${GITHUB_ISSUE_SEARCH},
          "documize": ${DOCUMIZE_SEARCH},
          "rocketchat": ${ROCKET_CHAT_SEARCH}
        },
        "login": ${LOGIN_FEATURE}
      }
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${NAME}-app-config${SUFFIX}
    labels:
      build: ${NAME}-static${SUFFIX}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  spec:
    runPolicy: SerialLatestOnly
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${VERSION}
    postCommit: {}
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 2
        memory: 4Gi
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: 'web'
      type: Git
      configMaps:
        - configMap:
            name: ${NAME}-app-config${SUFFIX}
          destinationDir: '/tmp/src/config'
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
                      # very important to increase nodes default memory limit to handle
                      # all the pages gatsby creates
        - name: NODE_OPTIONS
          value: --max_old_space_size=1000
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: devhub-gh-token
              key: GITHUB_TOKEN
        - name: GATSBY_ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: devhub-algolia-build
              key: GATSBY_ALGOLIA_APP_ID
        - name: ALGOLIA_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: devhub-algolia-build
              key: ALGOLIA_ADMIN_KEY
        - name: GATSBY_ALGOLIA_SEARCH_KEY
          valueFrom:
            secretKeyRef:
              name: devhub-algolia-build
              key: GATSBY_ALGOLIA_SEARCH_KEY
        - name: GATSBY_ALGOLIA_INDEX_NAME
          value: ${GATSBY_ALGOLIA_INDEX_NAME}
        - name: EVENT_BRITE_API_KEY
          valueFrom:
            secretKeyRef:
              name: devhub-eventbrite-token
              key: EVENT_BRITE_API_KEY
        from:
          kind: ImageStreamTag
          name: caddy-s2i-builder:latest
        incremental: false
      type: Source
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: devhub-app-web
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A name suffix used for all objects
  displayName: Suffix
  name: GATSBY_ALGOLIA_INDEX_NAME
  required: false
  value: Devhub-Algolia-local
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: SOURCE_REPOSITORY_URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/devhub-app-web.git
- description: SOURCE_REPOSITORY_REF
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: ''
- description: Enable Github Issue Searching (requires search gate to be enabled on runtime)
  displayName: Github Issue Search
  name: GITHUB_ISSUE_SEARCH
  value: "false"
- description: Enable Documize Searching (requires search gate to be enabled on runtime)
  displayName: Documize Search
  name: DOCUMIZE_SEARCH
  value: "false"
- description: Enable Rocket.Chat Searching (requires search gate to be enabled on runtime)
  displayName: Rocket.Chat Search
  name: ROCKET_CHAT_SEARCH
  value: "false"
- description: Enable Logging into Keycloak Services (requires keycloak integration details to be set up at runtime)
  displayName: Login Feature
  name: LOGIN_FEATURE
  value: "false"
